name: Update Data

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
         persist-credentials: false
         fetch-depth: 0
      - name: upload
        run: |
          ls
          pwd
          bash transfer-to-branch-results.sh
      - name: commit change
        run: |
          git checkout results
          mv results/* .
          git add -A
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          git commit -m "$d"
      - name: Github Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          branch: results
