name: Update Data

on:
  workflow_dispatch:
    
  push:
    branches:
      - main

jobs:
  transfer-to-branch-results:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
         persist-credentials: false
         fetch-depth: 0
      - name: upload
        run: bash transfer-to-branch-results.sh
      - name: commit change
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          git commit -m "$d"
      - name: Github Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          branch: results
  extract-folder-results:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
         persist-credentials: false
         fetch-depth: 0
         ref: results
      - run: mv results/* .
      - run: rmdir results
      - name: commit change
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          git commit -m "$d"
      - name: Github Push
        uses: ad-m/github-push-action@master
        with:
          directory: "."
          branch: results
